[workspace]

members = [
    "indy-credx",
    "indy-data-types",
    "indy-test-utils",
    "indy-utils",
    "bindgen"
    ]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
